var _dlRes = {
    "emptyAddress": "Please enter a postal code and/or city."
    , "unrecognizedAddress": "Unrecognized or ambiguous address."
    , "unrecognizedCity": "Unrecognized or ambiguous city."
    , "unrecognizedPostalCode": "Unrecognized or ambiguous postal code."
    , "viewAdditionalLocations": "Additional Locations"
    , "hideAdditionalLocations": "Hide Additional Locations"
    , "getDirections": "Get Directions"
    , "generalDirectionsError": "Error getting directions."
    , "annotation_500": "This provider has treated over 500 patients with Invisalign."
    , "annotation_1000": "This provider has treated over 1,000 patients with Invisalign."
    , "annotation_1500": "This provider has treated over 1,500 patients with Invisalign."
    , "annotation_2000": "This provider has treated over 2,000 patients with Invisalign."
    , "annotation_2500": "This provider has treated over 2,500 patients with Invisalign."
    , "annotation_4000": "This provider has treated over 4,000 patients with Invisalign."
    , "annotation_S": "This provider has achieved Silver status by treating between 11 - 20 patients within the last 12 months."
    , "annotation_G": "This provider has achieved Gold status by treating between 21-40 patients within the last 12 months."
    , "annotation_P": "This provider has achieved Platinum status by treating between 41-80 patients within the last 12 months."
    , "annotation_PE": "This provider has achieved Platinum Elite status by treating between 81-150 within the last 12 months."
    , "annotation_D": "This provider has achieved Diamond status by treating over 150 patients within the last 12 months."
    , "annotation_LARGE": "This provider is part of a group of Invisalign Providers."
    , "annotation_ITERO": "This provider uses the Invisalign iTero scanner to take 3D digital impressions of your teeth."
    , "annotation_TE": "This provider is experienced in Invisalign treatment for teenagers."
    , "annotation_VIVERA": "This provider is experienced in using Vivera retainers."
    , "annotation_CS": "This provider is a clinical speaker for the Invisalign system."
    , "legend_question": "What do these icons mean?"
    , "legend_title": "Key to Icons"
    , "pagerNext": "Next"
    , "pagerPrev": "Prev"
    , "pagerFirst": "First"
    , "pagerLast": "Last"
    , "resultsHeader": "{results} results"
    , "resultsMapHeaderCity": "Showing <b>{results}</b> Invisalign Providers in <span class='dlBlue'>\u0027{location}\u0027</span>"
    , "resultsMapHeaderAddress": "Showing <b>{results}</b> Invisalign Providers near <span class='dlBlue'>\u0027{location}\u0027</span>"
    , "resultsMapHeaderAdditionalLocations": "Showing {num} locations for {FullName}"
    , "directionsMapHeader": "Your estimated travel time is {duration} for {distance} of travel in {steps} steps."
    , "phoneLabel": "Phone"
    , "emailLabel": "E-mail"
    , "webLabel": "Web"
    , "distanceLabel": "Distance"
    , "viewOnMapLabel": "View On Map"
    , "viewContactInfoLabel": "View full contact details"
    , "viewFullProfileLabel": "View full contact details"
    , "startingAddress": "Starting Address"
    , "goButton": "Go"
    , "labelFrom": "From:"
    , "labelTo": "To:"
    , "labelBackToSR1": "\u003c Back to Doctor Locator Search Results"
    , "labelBackToSR2": "\u003c Search Again"
    , "labelDirections": "Directions"
    , "labelPrint": "Print"
    , "labelEmail": "Email"
    , "labelAdults": "Invisalign Adult"
    , "labelTeens": "Invisalign Teen"
    , "labelPostalCode": "Postal code:"
    , "labelAddress": "Address:"
    , "labelCity": "Town / City:"
    , "labelCountry": "Country:"
    , "labelSearch": "Show results"
    , "labelPleaseComplete": "Please complete the fields below:"
    , "labelNewSearch": "New Search"
    , "labelPrevious": "Previous"
    , "labelNext": "Next"
    , "labelPractitionerKey": "Practitioner Key"
    , "labelClickForAppointment": "Click for appointment"
    , "lableCallOn": "Or call on"
    , "labelBiography": "Biography"
    , "labelServerError": "Server error"
    , "labelNoResults": "No results found"
    , "label2000Description": "This provider has treated over 2000, 1000 or 500 patients with Invisalign."
    , "labelPEDescription": "This provider has treated a significant number of patients with Invisalign per year."
    , "labelTDescription": "This provider offers Invisalign for teenage patients."
    , "labelCSDescription": "This provider is a speaker at Align Technology events for clinical professionals."
    , "labelIOSDescription": "This provider offers iTero\u003csup\u003e®\u003c/sup\u003e intraoral scanning facilities.&nbsp;\u003ca href=\u0027itero_details.html\u0027 id=\u0027lightbox01\u0027\u003eRead more.\u003c/a\u003e"
    , "labelSortBy": "Sort by"
    , "labelSortExperience": "Experience"
    , "labelSortProximity": "Proximity"
    , "labelDoctorName": "Doctor's name"
    , "labelHome": "Home"
    , "nameTooShort": "The name should be at least three characters and without spaces."
    , "labelItero": "iTero<sup style='font-size:11px;'>®</sup> scanner"
    , "labelContactForm": "Request an appointment"
    , "labelIPDForm": "Register for an Invisalign Open Day"
    , "labelDoctorLocator": "Doctor locator"
    , "labelSearchNearMe": "Please use my location"
    , "labelList": "List"
    , "labelMap": "Map"
    , "labelShowOnMap": "Show on map"
    , "labelBackToResults": "Back to results"
    , "labelSearchShort": "Search"
    , "labelBack": "Back"
    , "countryLabel_gb": "United Kingdom"
    , "countryLabel_ie": "Ireland"
    , "countryLabel_de": "Germany"
    , "countryLabel_at": "Austria"
    , "countryLabel_ch": "Switzerland"
    , "countryLabel_it": "Italy"
    , "countryLabel_es": "Spain"
    , "searchCountry_gb": "UK"
    , "searchCountry_ie": "Ireland"
    , "searchCountry_de": "Germany"
    , "searchCountry_at": "Austria"
    , "searchCountry_ch": "Switzerland"
    , "searchCountry_it": "Italy"
    , "searchCountry_es": "Spain"
    , "labelDist_km": "km"
    , "labelDist_mi": "mi"
    , "labelZipError": "Unrecognized postal code. A valid postal code should look like: \"{sampleZip}\" and alternatively you can also search by city."
    , "labelAddress2": "Address"
    , "labelAboutThisOffice": "About This Office"
    , "labelMonday": "Monday"
    , "labelTuesday": "Tuesday"
    , "labelWednesday": "Wednesday"
    , "labelThursday": "Thursday"
    , "labelFriday": "Friday"
    , "labelSaturday": "Saturday"
    , "labelSunday": "Sunday"
    , "labelClosed": "closed"
    , "labelOfficeHours": "Office hours:"
    , "labelViveraLegend": "This Provider has prescribed a significant number of Vivera retainers for retention to patients finishing orthodontic treatment over the last year. <a href='/en/what-is-invisalign/Pages/ViveraRetainers.aspx'>Read more</a>."
    , "labelSortBy2": "Display search results by:"
    , "labelPracticeName": "Name of clinic:"
    , "labelAdvancedSearch": "Advanced Search"
    , "contact_page_title": "Appointment requests"
    , "contact_to": "To:"
    , "contact_subject": "Subject:"
    , "contact_request-info": "Request for Invisalign Appointment"
    , "contact_form_headernote": "Please complete the fields below. Fields with * are compulsory."
    , "contact_form_header_mandatory": ""
    , "contact_lbl_server_error": "Server error, try again later."
    , "contact_lbl_firstname": "First name*"
    , "contact_lbl_firstname_req": "Please fill in your first name"
    , "contact_lbl_lastname": "Last name*"
    , "contact_lbl_lastname_req": "Please fill in your last name"
    , "contact_lbl_email": "Email address*"
    , "contact_lbl_email_req": "Please fill in your email address"
    , "contact_lbl_email_regex": "Value is not a valid email address"
    , "contact_lbl_datebirth_req": "Please fill in your date of birth"
    , "contact_lbl_email_note": "Your email address will only be used to contact you regarding the request."
    , "contact_lbl_phone": "Phone Number*"
    , "contact_lbl_phone_req": "Please fill in your phone number"
    , "contact_lbl_contact_method": "Preferred Contact Method*"
    , "contact_lbl_preferred_time": "Best time to be contacted"
    , "contact_lbl_preferred_day": "Preferred day for an appointment"
    , "contact_lbl_preferred_time_app": "Preferred time for an appointment"
    , "contact_lbl_captcha": "Enter the text from the image"
    , "contact_lbl_captcha_req": "This field is required"
    , "contact_lbl_captcha_error": "Please, enter the text correctly"
    , "contact_lbl_event_req": "Select an event"
    , "contact_lbl_contact_method_req": "Please select a contact method"
    , "contact_lbl_offers_accept": "By ticking this box, you agree that we can pass your information on to your selected Invisalign Provider"
    , "contact_submit": "SUBMIT"
    , "contact_thankyou1": "Thank you - your email has been successfully sent!"
    , "contact_thankyou2": "You should expect to hear from the doctor’s office within 1-2 business days."
    , "contact_thankyou1a": "Thank you for registering your interest in attending our Open Day on [date]."
    , "contact_thankyou2a": "You will hear from our Practice Manager within 1-2 business days to confirm your appointment.  In the meantime, if you would like to talk to us please call on [phone]."
    , "contact_close": "Close"
    , "contact_ddlContactMethod_0": "- Select One -"
    , "contact_ddlContactMethod_1": "Email"
    , "contact_ddlContactMethod_2": "Phone"
    , "contact_ddlPreferredTime_0": "Time of day"
    , "contact_ddlPreferredTime_1": "Mornings"
    , "contact_ddlPreferredTime_2": "Afternoons"
    , "contact_ddlPreferredTime_3": "Evenings"
    , "contact_ddlPreferredDay_0": "Day of the week"
    , "contact_page_title1": "Register for this Invisalign event"
    , "contact_page_title2": "Register for an Invisalign Open Day"
    , "contact_request-info1": "Register for this Invisalign event"
    , "contact_request-info2": "Register me for the Invisalign Open Day - [date]"
    , "contact_daysofweek": "Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday"
    , "contact_monthsofyear": "January,February,March,April,May,June,July,August,September,October,November,December"
    , "contact_datebirth": "Date of birth*"
    , "contact_title": "Title"
    , "contact_mr": "Mr"
    , "contact_mrs": "Mrs"
    , "contact_ms": "Ms"
    , "contact_day": "Day"
    , "contact_month": "Month"
    , "contact_year": "Year"
    , "contact_special_requests": "Special requests"
    , "contact_disclaimer": "By ticking this box and clicking <b>SUBMIT</b>, I understand that I will be contacted by the certified Invisalign Provider(s) I have selected to make an appointment. I also agree to receive information about Invisalign treatment and from partners of Align Technology, Inc. by email, mobile phone, text or other means to which I consent. This information may contain special offers, information on local providers, and requests for feedback about your experience. If you prefer not to be contacted please click <b>CANCEL</b>. All information will be handled in accordance with Align’s <a href='{sub_privacy}' target='_blank'>Privacy Policy</a>."
    , "contact_select_to_5": "You can select up to 3 doctors in this appointment request. Simply go back to the results list and click the 'request an appointment' button for another doctor."
    , "contact_select_to_5_msg": "You can select up to 3 doctors in this appointment request."
    , "contact_cancel": "CANCEL"
};